//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "library_role")]
pub enum LibraryRole {
    #[sea_orm(string_value = "library_owner")]
    LibraryOwner,
    #[sea_orm(string_value = "library_editor")]
    LibraryEditor,
    #[sea_orm(string_value = "library_viewer")]
    LibraryViewer,
}
