/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DemoIdRouteImport } from './routes/demo.$id'
import { Route as LibrariesIndexRouteImport } from './routes/libraries.index'
import { Route as LibrariesLibraryIdBooksRouteImport } from './routes/libraries.$libraryId.books'
import { Route as LibrariesLibraryIdSettingsRouteImport } from './routes/libraries.$libraryId.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdRoute = DemoIdRouteImport.update({
  id: '/demo/$id',
  path: '/demo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdBooksRoute = LibrariesLibraryIdBooksRouteImport.update({
  id: '/libraries/$libraryId/books',
  path: '/libraries/$libraryId/books',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdSettingsRoute =
  LibrariesLibraryIdSettingsRouteImport.update({
    id: '/libraries/$libraryId/settings',
    path: '/libraries/$libraryId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/demo/$id': typeof DemoIdRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/libraries/$libraryId/books': typeof LibrariesLibraryIdBooksRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/demo/$id': typeof DemoIdRoute
  '/libraries': typeof LibrariesIndexRoute
  '/libraries/$libraryId/books': typeof LibrariesLibraryIdBooksRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/demo/$id': typeof DemoIdRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/libraries/$libraryId/books': typeof LibrariesLibraryIdBooksRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/demo/$id'
    | '/libraries/'
    | '/libraries/$libraryId/books'
    | '/libraries/$libraryId/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/demo/$id'
    | '/libraries'
    | '/libraries/$libraryId/books'
    | '/libraries/$libraryId/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/demo/$id'
    | '/libraries/'
    | '/libraries/$libraryId/books'
    | '/libraries/$libraryId/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  DemoIdRoute: typeof DemoIdRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
  LibrariesLibraryIdBooksRoute: typeof LibrariesLibraryIdBooksRoute
  LibrariesLibraryIdSettingsRoute: typeof LibrariesLibraryIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$id': {
      id: '/demo/$id'
      path: '/demo/$id'
      fullPath: '/demo/$id'
      preLoaderRoute: typeof DemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/books': {
      id: '/libraries/$libraryId/books'
      path: '/libraries/$libraryId/books'
      fullPath: '/libraries/$libraryId/books'
      preLoaderRoute: typeof LibrariesLibraryIdBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/settings': {
      id: '/libraries/$libraryId/settings'
      path: '/libraries/$libraryId/settings'
      fullPath: '/libraries/$libraryId/settings'
      preLoaderRoute: typeof LibrariesLibraryIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  DemoIdRoute: DemoIdRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
  LibrariesLibraryIdBooksRoute: LibrariesLibraryIdBooksRoute,
  LibrariesLibraryIdSettingsRoute: LibrariesLibraryIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
