/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DemoIdRouteImport } from './routes/demo.$id'
import { Route as LibrariesIndexRouteImport } from './routes/libraries.index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminSettingsGeneralRouteImport } from './routes/admin.settings.general'
import { Route as AdminSettingsGenresRouteImport } from './routes/admin.settings.genres'
import { Route as AdminSettingsMediaTypesRouteImport } from './routes/admin.settings.media-types'
import { Route as LibrariesLibraryIdSettingsRouteImport } from './routes/libraries.$libraryId.settings'
import { Route as LibrariesLibraryIdBooksIndexRouteImport } from './routes/libraries.$libraryId.books.index'
import { Route as LibrariesLibraryIdBooksAddRouteImport } from './routes/libraries.$libraryId.books.add'
import { Route as LibrariesLibraryIdBooksNewRouteImport } from './routes/libraries.$libraryId.books.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIdRoute = DemoIdRouteImport.update({
  id: '/demo/$id',
  path: '/demo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesIndexRoute = LibrariesIndexRouteImport.update({
  id: '/libraries/',
  path: '/libraries/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/admin/settings/',
  path: '/admin/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/admin/settings/general',
  path: '/admin/settings/general',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsGenresRoute = AdminSettingsGenresRouteImport.update({
  id: '/admin/settings/genres',
  path: '/admin/settings/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsMediaTypesRoute = AdminSettingsMediaTypesRouteImport.update({
  id: '/admin/settings/media-types',
  path: '/admin/settings/media-types',
  getParentRoute: () => rootRouteImport,
} as any)
const LibrariesLibraryIdSettingsRoute =
  LibrariesLibraryIdSettingsRouteImport.update({
    id: '/libraries/$libraryId/settings',
    path: '/libraries/$libraryId/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibrariesLibraryIdBooksIndexRoute =
  LibrariesLibraryIdBooksIndexRouteImport.update({
    id: '/libraries/$libraryId/books/',
    path: '/libraries/$libraryId/books/',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibrariesLibraryIdBooksAddRoute =
  LibrariesLibraryIdBooksAddRouteImport.update({
    id: '/libraries/$libraryId/books/add',
    path: '/libraries/$libraryId/books/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibrariesLibraryIdBooksNewRoute =
  LibrariesLibraryIdBooksNewRouteImport.update({
    id: '/libraries/$libraryId/books/new',
    path: '/libraries/$libraryId/books/new',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/demo/$id': typeof DemoIdRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/genres': typeof AdminSettingsGenresRoute
  '/admin/settings/media-types': typeof AdminSettingsMediaTypesRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/libraries/$libraryId/books/add': typeof LibrariesLibraryIdBooksAddRoute
  '/libraries/$libraryId/books/new': typeof LibrariesLibraryIdBooksNewRoute
  '/libraries/$libraryId/books/': typeof LibrariesLibraryIdBooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/demo/$id': typeof DemoIdRoute
  '/libraries': typeof LibrariesIndexRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/genres': typeof AdminSettingsGenresRoute
  '/admin/settings/media-types': typeof AdminSettingsMediaTypesRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/libraries/$libraryId/books/add': typeof LibrariesLibraryIdBooksAddRoute
  '/libraries/$libraryId/books/new': typeof LibrariesLibraryIdBooksNewRoute
  '/libraries/$libraryId/books': typeof LibrariesLibraryIdBooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/demo/$id': typeof DemoIdRoute
  '/libraries/': typeof LibrariesIndexRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/genres': typeof AdminSettingsGenresRoute
  '/admin/settings/media-types': typeof AdminSettingsMediaTypesRoute
  '/libraries/$libraryId/settings': typeof LibrariesLibraryIdSettingsRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/libraries/$libraryId/books/add': typeof LibrariesLibraryIdBooksAddRoute
  '/libraries/$libraryId/books/new': typeof LibrariesLibraryIdBooksNewRoute
  '/libraries/$libraryId/books/': typeof LibrariesLibraryIdBooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/demo/$id'
    | '/libraries/'
    | '/admin/settings/general'
    | '/admin/settings/genres'
    | '/admin/settings/media-types'
    | '/libraries/$libraryId/settings'
    | '/admin/settings/'
    | '/libraries/$libraryId/books/add'
    | '/libraries/$libraryId/books/new'
    | '/libraries/$libraryId/books/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/demo/$id'
    | '/libraries'
    | '/admin/settings/general'
    | '/admin/settings/genres'
    | '/admin/settings/media-types'
    | '/libraries/$libraryId/settings'
    | '/admin/settings'
    | '/libraries/$libraryId/books/add'
    | '/libraries/$libraryId/books/new'
    | '/libraries/$libraryId/books'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/setup'
    | '/demo/$id'
    | '/libraries/'
    | '/admin/settings/general'
    | '/admin/settings/genres'
    | '/admin/settings/media-types'
    | '/libraries/$libraryId/settings'
    | '/admin/settings/'
    | '/libraries/$libraryId/books/add'
    | '/libraries/$libraryId/books/new'
    | '/libraries/$libraryId/books/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  DemoIdRoute: typeof DemoIdRoute
  LibrariesIndexRoute: typeof LibrariesIndexRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsGenresRoute: typeof AdminSettingsGenresRoute
  AdminSettingsMediaTypesRoute: typeof AdminSettingsMediaTypesRoute
  LibrariesLibraryIdSettingsRoute: typeof LibrariesLibraryIdSettingsRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
  LibrariesLibraryIdBooksAddRoute: typeof LibrariesLibraryIdBooksAddRoute
  LibrariesLibraryIdBooksNewRoute: typeof LibrariesLibraryIdBooksNewRoute
  LibrariesLibraryIdBooksIndexRoute: typeof LibrariesLibraryIdBooksIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/$id': {
      id: '/demo/$id'
      path: '/demo/$id'
      fullPath: '/demo/$id'
      preLoaderRoute: typeof DemoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/': {
      id: '/libraries/'
      path: '/libraries'
      fullPath: '/libraries/'
      preLoaderRoute: typeof LibrariesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/admin/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/general': {
      id: '/admin/settings/general'
      path: '/admin/settings/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/genres': {
      id: '/admin/settings/genres'
      path: '/admin/settings/genres'
      fullPath: '/admin/settings/genres'
      preLoaderRoute: typeof AdminSettingsGenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/media-types': {
      id: '/admin/settings/media-types'
      path: '/admin/settings/media-types'
      fullPath: '/admin/settings/media-types'
      preLoaderRoute: typeof AdminSettingsMediaTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/settings': {
      id: '/libraries/$libraryId/settings'
      path: '/libraries/$libraryId/settings'
      fullPath: '/libraries/$libraryId/settings'
      preLoaderRoute: typeof LibrariesLibraryIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/books/': {
      id: '/libraries/$libraryId/books/'
      path: '/libraries/$libraryId/books'
      fullPath: '/libraries/$libraryId/books/'
      preLoaderRoute: typeof LibrariesLibraryIdBooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/books/add': {
      id: '/libraries/$libraryId/books/add'
      path: '/libraries/$libraryId/books/add'
      fullPath: '/libraries/$libraryId/books/add'
      preLoaderRoute: typeof LibrariesLibraryIdBooksAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/libraries/$libraryId/books/new': {
      id: '/libraries/$libraryId/books/new'
      path: '/libraries/$libraryId/books/new'
      fullPath: '/libraries/$libraryId/books/new'
      preLoaderRoute: typeof LibrariesLibraryIdBooksNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  DemoIdRoute: DemoIdRoute,
  LibrariesIndexRoute: LibrariesIndexRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsGenresRoute: AdminSettingsGenresRoute,
  AdminSettingsMediaTypesRoute: AdminSettingsMediaTypesRoute,
  LibrariesLibraryIdSettingsRoute: LibrariesLibraryIdSettingsRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
  LibrariesLibraryIdBooksAddRoute: LibrariesLibraryIdBooksAddRoute,
  LibrariesLibraryIdBooksNewRoute: LibrariesLibraryIdBooksNewRoute,
  LibrariesLibraryIdBooksIndexRoute: LibrariesLibraryIdBooksIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
